FROM golang:1.21 AS go-builder
WORKDIR /app
COPY ./golang/ .
RUN go run main.go
FROM python:3.10.2-slim
WORKDIR /app
COPY ./python/ ./python/
RUN pip install --no-cache-dir -r ./python/requirements.txt
EXPOSE 3000
CMD ["python", "./python/server_example.py"]
