version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python ./python/server_example.py
